### ISSUE TITLE
Menu Model Errors

### ISSUE THREAD

**Issue by V-arch50** [R-K-Associates/Valuation-Intelligent-System#2]
MenuModel1 : When the third party link is redirected then it is not taking the links fully due to which there is a problem in loading URL/PDF
MenuModel2 : When the status is selected as Inactive then also the menu is showing at the Front End though it is inactive at the admin back-end.
MenuModel3 :  In some of the menus, after selecting the status as Inactive and submitting the same then also it is showing the Active status.

Additionally the links and urls which were uploaded at the menu model are sometimes getting crashed or not be able to open, but the same URL or link when opened separately it is getting launched smoothly

Please see the attached file with same.
![MenuModel1](https://user-images.githubusercontent.com/62279166/83503971-88539f80-a4e1-11ea-957f-5429ff77a9c4.JPG)
![MenuModel2](https://user-images.githubusercontent.com/62279166/83503974-8984cc80-a4e1-11ea-84e0-9d240faaf69b.JPG)
![MenuModel3](https://user-images.githubusercontent.com/62279166/83503975-8a1d6300-a4e1-11ea-8782-cd0239b7c26f.JPG)

**Comment by Mgmangal** [comment]
Hello Sir,

Today change these directory file

=========== change note============
application/views/admin/admin_leads/documentation.php

application/views/admin/admin_leads/ba_documentation.php

application/controllers/adminpanel/leads/LeadManagement.php



=========== change official email phone============
application/views/admin/hr_admin/appointment.php

application/views/admin/hr_admin/other_info.php

application/controllers/adminpanel/hr/EmployeeManageByhrAdmin.php


=========== change one title redirect============
application/views/admin/top_new_external_header.php

application/controllers/Admin/Welcome.php


=========== change status active inactive============
application/views/admin/menu/add_submenu_state_level_two.php

application/views/admin/menu/add_submenu_state_level_one.php

application/controllers/Admin/Menu.php



THANKS & REGARDS,
 Mangal Singh Yadav

**Comment by V-arch50** [comment]
Thanks Mangal
